name: cucumber-selenium-schedule
on : 
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Code
        uses: actions/checkout@v4
        env : 
          DEFAULT_BRANCH: development
      - name: my-tests
        run: echo "Hello My Cucumber-Selenium"
